pull_request_rules:
- name: Automatic approve on Sourcery AI PR
  conditions:
  - author~=^sourcery.*$
  - check-success=workflow
  actions:
    review:
      type: APPROVE

- name: Automatic merge on approval of Sourcery AI PR
  conditions:
  - author~=^sourcery.*$
  - check-success=workflow
  actions:
    merge:
      method: merge

- name: Automatic approve my PR
  conditions:
  - author~=^bengosney$
  - check-success=workflow
  actions:
    review:
      type: APPROVE

- name: Automatic merge on approval
  conditions:
  - author~=^bengosney$
  - check-success=workflow
  actions:
    merge:
      method: merge
