version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
    - image: cimg/python:3.12
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - python/install-packages:
        pip-dependency-file: requirements.dev.txt
        pkg-manager: pip
    - run:
        name: Run tests
        command: pytest src/*.py

workflows:
  testing:
    jobs:
    - build-and-test
