name: Update AoC Badges
on:
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
          
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.USERID }}
          session: ${{ secrets.AOC_SESSION }}
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
